// Gerado a partir de src/App.jsx (POOL via buildPool) — dados necessários
// para simular a jornada no servidor (scoreLineup). Mantém em sincronia se
// adicionares/alterares cartas ou stats no jogo.
import type { Rarity } from "./cardpool.ts";

export interface JornadaCard {
  id: string;
  name: string;
  rarity: Rarity;
  team: string | null;
  isClub: boolean;
  isCaster: boolean;
  edition: string | null;
  ref: string | null;
  casterRef: string | null;
  v: number | null;
  mg: number | null;
}

export const JORNADA_CARDS: JornadaCard[] = [
  {
    "id": "club-benfica",
    "name": "SL Benfica Esports",
    "rarity": "epica",
    "team": "benfica",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 68.8,
    "mg": 5.38
  },
  {
    "id": "club-sporting",
    "name": "Sporting CP | IGW",
    "rarity": "rara",
    "team": "sporting",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 25,
    "mg": 6.06
  },
  {
    "id": "club-porto",
    "name": "FC Porto | Luna",
    "rarity": "rara",
    "team": "porto",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 44.6,
    "mg": 5.03
  },
  {
    "id": "club-braga",
    "name": "SC Braga | EGN ESPORTS",
    "rarity": "comum",
    "team": "braga",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 13.7,
    "mg": 3.32
  },
  {
    "id": "club-santaclara",
    "name": "Santa Clara",
    "rarity": "epica",
    "team": "santaclara",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 70.7,
    "mg": 6.13
  },
  {
    "id": "club-estrela",
    "name": "Estrela Amadora Fluxo W7M",
    "rarity": "rara",
    "team": "estrela",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 40,
    "mg": 4.24
  },
  {
    "id": "club-estoril",
    "name": "Estoril Praia",
    "rarity": "comum",
    "team": "estoril",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 33.3,
    "mg": 4.72
  },
  {
    "id": "club-gilvicente",
    "name": "Gil Vicente FC",
    "rarity": "comum",
    "team": "gilvicente",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 41.2,
    "mg": 5.35
  },
  {
    "id": "club-arouca",
    "name": "FC Arouca by Quest | OGM",
    "rarity": "rara",
    "team": "arouca",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 40,
    "mg": 5.65
  },
  {
    "id": "club-tondela",
    "name": "CD Tondela | Apogee",
    "rarity": "comum",
    "team": "tondela",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 43.8,
    "mg": 6.31
  },
  {
    "id": "club-moreirense",
    "name": "Moreirense FC",
    "rarity": "rara",
    "team": "moreirense",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 68.2,
    "mg": 5.91
  },
  {
    "id": "club-famalicao",
    "name": "FC Famalicão",
    "rarity": "comum",
    "team": "famalicao",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 39.3,
    "mg": 4.74
  },
  {
    "id": "club-vitoria",
    "name": "Vitória SC | ISG",
    "rarity": "comum",
    "team": "vitoria",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 23.8,
    "mg": 3.36
  },
  {
    "id": "club-rioave",
    "name": "Rio Ave FC",
    "rarity": "comum",
    "team": "rioave",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 31.3,
    "mg": 5.56
  },
  {
    "id": "club-casapia",
    "name": "Casa Pia AC | Grow uP",
    "rarity": "comum",
    "team": "casapia",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 25,
    "mg": 4.15
  },
  {
    "id": "club-nacional",
    "name": "CD Nacional",
    "rarity": "comum",
    "team": "nacional",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 6.7,
    "mg": 4.4
  },
  {
    "id": "club-afs",
    "name": "AFS | TxT Gaming",
    "rarity": "rara",
    "team": "afs",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 45,
    "mg": 4.53
  },
  {
    "id": "club-alverca",
    "name": "FC Alverca | GOAT",
    "rarity": "comum",
    "team": "alverca",
    "isClub": true,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 47.1,
    "mg": 6.59
  },
  {
    "id": "pl-leks",
    "name": "Leks",
    "rarity": "epica",
    "team": "benfica",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 87.5,
    "mg": 6.13
  },
  {
    "id": "pl-marqzou",
    "name": "MarQzou",
    "rarity": "rara",
    "team": "benfica",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 50,
    "mg": 4.63
  },
  {
    "id": "pl-tundi",
    "name": "Tundi",
    "rarity": "epica",
    "team": "santaclara",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 57.1,
    "mg": 6.57
  },
  {
    "id": "pl-gugaferraz",
    "name": "GugaFerraz",
    "rarity": "epica",
    "team": "santaclara",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 84.2,
    "mg": 5.68
  },
  {
    "id": "pl-diogopeyroteo",
    "name": "DiogoPeyroteo9",
    "rarity": "rara",
    "team": "sporting",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 50,
    "mg": 5.11
  },
  {
    "id": "pl-bret4o",
    "name": "bret4o",
    "rarity": "comum",
    "team": "sporting",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 0,
    "mg": 7
  },
  {
    "id": "pl-peter16",
    "name": "Peter16",
    "rarity": "rara",
    "team": "porto",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 42.9,
    "mg": 5.43
  },
  {
    "id": "pl-diogosilva",
    "name": "Diogo Silva",
    "rarity": "rara",
    "team": "porto",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 46.2,
    "mg": 4.62
  },
  {
    "id": "pl-jperes99",
    "name": "JPeres99",
    "rarity": "comum",
    "team": "braga",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 27.3,
    "mg": 3.64
  },
  {
    "id": "pl-rikhard",
    "name": "Rikhard",
    "rarity": "comum",
    "team": "braga",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 0,
    "mg": 3
  },
  {
    "id": "pl-mike27",
    "name": "Mike_27",
    "rarity": "comum",
    "team": "estrela",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 20,
    "mg": 3.6
  },
  {
    "id": "pl-gueric",
    "name": "Gueric",
    "rarity": "epica",
    "team": "estrela",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 60,
    "mg": 4.87
  },
  {
    "id": "pl-lucanr1",
    "name": "Luca-NR1",
    "rarity": "epica",
    "team": "moreirense",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 68.2,
    "mg": 5.91
  },
  {
    "id": "pl-licapu",
    "name": "Licapu",
    "rarity": "comum",
    "team": "estoril",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 33.3,
    "mg": 4.72
  },
  {
    "id": "pl-zitsubasa",
    "name": "Zitsubasa",
    "rarity": "rara",
    "team": "gilvicente",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 41.2,
    "mg": 5.35
  },
  {
    "id": "pl-jotapb10",
    "name": "Jotapb10",
    "rarity": "rara",
    "team": "arouca",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 40,
    "mg": 5.65
  },
  {
    "id": "pl-guiddias",
    "name": "Guiddias_14",
    "rarity": "comum",
    "team": "arouca",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 0,
    "mg": 0
  },
  {
    "id": "pl-darkley11",
    "name": "Darkley11",
    "rarity": "rara",
    "team": "tondela",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 43.8,
    "mg": 6.31
  },
  {
    "id": "pl-vinagrolih",
    "name": "Vinagrolih",
    "rarity": "comum",
    "team": "famalicao",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 28.6,
    "mg": 3.57
  },
  {
    "id": "pl-rodr7gol",
    "name": "Rodr7gol",
    "rarity": "rara",
    "team": "famalicao",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 50,
    "mg": 5.9
  },
  {
    "id": "pl-dekass",
    "name": "Dekass",
    "rarity": "comum",
    "team": "vitoria",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 14.3,
    "mg": 3.71
  },
  {
    "id": "pl-skreibar",
    "name": "Skreibar",
    "rarity": "comum",
    "team": "vitoria",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 33.3,
    "mg": 3
  },
  {
    "id": "pl-phoenix",
    "name": "phoenix3687",
    "rarity": "comum",
    "team": "rioave",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 31.3,
    "mg": 5.56
  },
  {
    "id": "pl-rickyp",
    "name": "RickyP",
    "rarity": "comum",
    "team": "rioave",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 0,
    "mg": 0
  },
  {
    "id": "pl-godrafa",
    "name": "GodRafa",
    "rarity": "comum",
    "team": "casapia",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 50,
    "mg": 5.3
  },
  {
    "id": "pl-ggrilo",
    "name": "ggrilo_10",
    "rarity": "comum",
    "team": "casapia",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 0,
    "mg": 3
  },
  {
    "id": "pl-canha14",
    "name": "Canha14",
    "rarity": "comum",
    "team": "nacional",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 6.7,
    "mg": 4.4
  },
  {
    "id": "pl-jsilva29",
    "name": "JSilva29_",
    "rarity": "rara",
    "team": "afs",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 50,
    "mg": 4.86
  },
  {
    "id": "pl-npena80",
    "name": "Npena80",
    "rarity": "comum",
    "team": "afs",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 40,
    "mg": 4.2
  },
  {
    "id": "pl-giobundyy",
    "name": "Giobundyy",
    "rarity": "rara",
    "team": "alverca",
    "isClub": false,
    "isCaster": false,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": 47.1,
    "mg": 6.59
  },
  {
    "id": "cast-donpablo",
    "name": "Don Pablo",
    "rarity": "epica",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": null,
    "mg": null
  },
  {
    "id": "cast-pickywiky",
    "name": "PickyWiky",
    "rarity": "epica",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": null,
    "mg": null
  },
  {
    "id": "cast-dantas",
    "name": "Dantas",
    "rarity": "rara",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": null,
    "mg": null
  },
  {
    "id": "cast-mucha",
    "name": "Mucha",
    "rarity": "rara",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": null,
    "mg": null
  },
  {
    "id": "cast-zeny",
    "name": "Zeny",
    "rarity": "rara",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": null,
    "mg": null
  },
  {
    "id": "cast-loureiro",
    "name": "Loureiro",
    "rarity": "rara",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": null,
    "ref": null,
    "casterRef": null,
    "v": null,
    "mg": null
  },
  {
    "id": "sp-leks-finals",
    "name": "Leks",
    "rarity": "lendaria",
    "team": "benfica",
    "isClub": false,
    "isCaster": false,
    "edition": "FINALS 25/26",
    "ref": "leks",
    "casterRef": null,
    "v": 87.5,
    "mg": 6.13
  },
  {
    "id": "sp-marqzou-finals",
    "name": "MarQzou",
    "rarity": "lendaria",
    "team": "benfica",
    "isClub": false,
    "isCaster": false,
    "edition": "FINALS 25/26",
    "ref": "marqzou",
    "casterRef": null,
    "v": 50,
    "mg": 4.63
  },
  {
    "id": "sp-benfica-finals",
    "name": "SL Benfica Esports",
    "rarity": "lendaria",
    "team": "benfica",
    "isClub": true,
    "isCaster": false,
    "edition": "FINALS 25/26",
    "ref": null,
    "casterRef": null,
    "v": null,
    "mg": null
  },
  {
    "id": "sp-tundi-taca",
    "name": "Tundi",
    "rarity": "lendaria",
    "team": "santaclara",
    "isClub": false,
    "isCaster": false,
    "edition": "TAÇA eLIGA",
    "ref": "tundi",
    "casterRef": null,
    "v": 57.1,
    "mg": 6.57
  },
  {
    "id": "sp-leks-e1",
    "name": "Leks",
    "rarity": "epica",
    "team": "benfica",
    "isClub": false,
    "isCaster": false,
    "edition": "ETAPA 1",
    "ref": "leks",
    "casterRef": null,
    "v": 87.5,
    "mg": 6.13
  },
  {
    "id": "sp-marqzou-e1",
    "name": "MarQzou",
    "rarity": "epica",
    "team": "benfica",
    "isClub": false,
    "isCaster": false,
    "edition": "ETAPA 1",
    "ref": "marqzou",
    "casterRef": null,
    "v": 50,
    "mg": 4.63
  },
  {
    "id": "sp-guga-e2",
    "name": "GugaFerraz",
    "rarity": "epica",
    "team": "santaclara",
    "isClub": false,
    "isCaster": false,
    "edition": "ETAPA 2",
    "ref": "gugaferraz",
    "casterRef": null,
    "v": 84.2,
    "mg": 5.68
  },
  {
    "id": "sp-gueric-e3",
    "name": "Gueric",
    "rarity": "epica",
    "team": "estrela",
    "isClub": false,
    "isCaster": false,
    "edition": "ETAPA 3",
    "ref": "gueric",
    "casterRef": null,
    "v": 60,
    "mg": 4.87
  },
  {
    "id": "sp-benfica-e1",
    "name": "SL Benfica Esports",
    "rarity": "epica",
    "team": "benfica",
    "isClub": true,
    "isCaster": false,
    "edition": "ETAPA 1",
    "ref": null,
    "casterRef": null,
    "v": null,
    "mg": null
  },
  {
    "id": "sp-santaclara-e2",
    "name": "Santa Clara",
    "rarity": "epica",
    "team": "santaclara",
    "isClub": true,
    "isCaster": false,
    "edition": "ETAPA 2",
    "ref": null,
    "casterRef": null,
    "v": null,
    "mg": null
  },
  {
    "id": "sp-estrela-e3",
    "name": "Estrela Amadora Fluxo W7M",
    "rarity": "epica",
    "team": "estrela",
    "isClub": true,
    "isCaster": false,
    "edition": "ETAPA 3",
    "ref": null,
    "casterRef": null,
    "v": null,
    "mg": null
  },
  {
    "id": "sp-donpablo-gf",
    "name": "Don Pablo",
    "rarity": "epica",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": "GRANDE FINAL",
    "ref": null,
    "casterRef": "donpablo",
    "v": null,
    "mg": null
  },
  {
    "id": "sp-pickywiky-gf",
    "name": "PickyWiky",
    "rarity": "epica",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": "GRANDE FINAL",
    "ref": null,
    "casterRef": "pickywiky",
    "v": null,
    "mg": null
  },
  {
    "id": "sp-dantas-gf",
    "name": "Dantas",
    "rarity": "epica",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": "GRANDE FINAL",
    "ref": null,
    "casterRef": "dantas",
    "v": null,
    "mg": null
  },
  {
    "id": "sp-mucha-gf",
    "name": "Mucha",
    "rarity": "epica",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": "GRANDE FINAL",
    "ref": null,
    "casterRef": "mucha",
    "v": null,
    "mg": null
  },
  {
    "id": "sp-zeny-gf",
    "name": "Zeny",
    "rarity": "epica",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": "GRANDE FINAL",
    "ref": null,
    "casterRef": "zeny",
    "v": null,
    "mg": null
  },
  {
    "id": "sp-loureiro-gf",
    "name": "Loureiro",
    "rarity": "epica",
    "team": null,
    "isClub": false,
    "isCaster": true,
    "edition": "GRANDE FINAL",
    "ref": null,
    "casterRef": "loureiro",
    "v": null,
    "mg": null
  }
];
